config/routes.rb
Gmap::Application.routes.draw do
  resources :locations

  get "homepage/start"

  root :to => 'homepage#start'

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :gmaps, :latitude, :longitude, :name
  acts_as_gmappable

  def gmaps4rails_address
    address
  end
  def gmaps4rails_infowindow
    "<h4>#{name}</h4>" << "<h4>#{address}</h4>"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def start
    @locations = Location.all
    @json = Location.all.to_gmaps4rails
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @json = Location.all.to_gmaps4rails
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/homepage/start.html.erb
<!DOCTYPE html>
<html>

<head>
  <style>
      .lineone{
          border-bottom: 6px solid #B41407;
          margin-top: 10px;
      }

       h1{
           font-size: 36px;
       }
       .map_container
      {
          width:805px;
          height:220px;
          overflow:scroll;
           padding: 3px 66px 6px 66px;
      }

      .buttons{
          padding-bottom: 1em;
          padding-top: 1em;
      }

      .button-one{
          background-color: #B41407;
          border: 0 none;
          color: #FFFFFF;
          padding: 0.5em 2em;
          float:left;
          margin-left: 9px;
      }


  </style>
  <script>
      function OpenInNewTab(url )
      {
          var win=window.open(url, '_blank');
          win.focus();
      }
  </script>

</head>

<body>
<div class="container">
<h1>
  Hyderabad Ruby
</h1>
<div class = "lineone"></div>



  <%= gmaps4rails(@json) %>


<div class = "lineone"></div>
  <div class="buttons">
    <p>Future Meetup :</p>
  <button type="button" onclick="OpenInNewTab('http://www.meetup.com/RubyHyderabad/')" class="button-one">22.02.14</button>&nbsp;
  <button type="button" onclick="OpenInNewTab('http://www.meetup.com/RubyHyderabad/')" class="button-one">08.03.14</button>&nbsp;
  <button type="button" onclick="OpenInNewTab('http://www.meetup.com/RubyHyderabad/')" class="button-one">22.0314</button>
  </div>
  <div class="buttons">
    <p>Past Meetup :</p>
    <button type="button" onclick="OpenInNewTab('http://www.meetup.com/RubyHyderabad/')" class="button-one">08.02.14</button>&nbsp;
    <button type="button" onclick="OpenInNewTab('http://www.meetup.com/RubyHyderabad/')" class="button-one">25.01.14</button>&nbsp;
    <button type="button" onclick="OpenInNewTab('http://www.meetup.com/RubyHyderabad/')" class="button-one">11.01.14</button>
  </div>
<div class = "lineone"></div>
  <h4>Groups</h4>
  <div class="buttons">
    <p>Meetup :</p>
    <button type="button" onclick="OpenInNewTab('http://www.meetup.com/RubyHyderabad/')" class="button-one">Ruby Hyderabad</button>&nbsp;
    <button type="button" onclick="OpenInNewTab('http://www.meetup.com/RubyHyderabad/')" class="button-one">Ruby Hyderabad</button>&nbsp;
  </div>
  <div class="buttons">
    <p>Twitter :</p>
    <button type="button" onclick="OpenInNewTab('https://twitter.com/HydRuby')" class="button-one">@HydRuby</button>&nbsp;
    <button type="button" onclick="OpenInNewTab('https://twitter.com/HydRuby')" class="button-one">@HydRuby</button>&nbsp;
  </div>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gmap</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= yield :scripts %>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :gmaps %><br />
    <%= f.check_box :gmaps %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<%= gmaps4rails(@json) %>
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Gmaps</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.address %></td>
    <td><%= location.longitude %></td>
    <td><%= location.latitude %></td>
    <td><%= location.gmaps %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Address:</b>
  <%= @location.address %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Gmaps:</b>
  <%= @location.gmaps %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>